version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: '02:00'
    timezone: "Europe/Moscow"
    day: "saturday"
  groups:
    "PyPi updates":
      patterns:
        - "*"
  target-branch: master
